### ISSUE TITLE
Summary: Grade = Meets Expectations

### ISSUE THREAD

**Issue by jordanwillis** [catvander/prj-rev-bwfs-dasmoto#5]
Overall, you did a fantastic job on this project!  Both your HTML and CSS look really good and I like that you included `alt` attributes in your image elements.  I did notice that Frame header was white and not visible on the page, so I would recommend revisiting that and seeing what's going on.

Take a look at my other feedback and see if you can start practicing my recommendations on your future projects.  It will pay huge dividends down the road!

**Comment by catvander** [comment]
Many thx for the detailed feedback.
